pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output

analyzers:
  joints:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Joints'
    discard_stale: true
    timeout: 5.0
    regex: '.*_joint$'    
