obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.12, -0.22], [-0.12, 0.22], [0.25, 0.22], [0.25, -0.22]]
#robot_radius: 0.25
inflation_radius: 0.2
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
